# This is a basic workflow to help you get started with Actions

name: YouTube Live to M3U

# Controls when the action will run.
on:
  schedule:
    - cron: '0 0/3 * * *'
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies if any
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any other dependencies here if needed
          # pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: Run YouTube_Live.py
        run: |
          python YouTube_Live.py

      - name: git add
        run: |
          git add -A
          ls -la

      - name: commit & push
        run: |
          git commit -m "Link updated"
          git push
